import type { CampaignDetail } from './queries'

/**
 * Hardcoded snapshot of the seeded `rseth-2026-04` campaign. Used as a
 * last-resort fallback when the local Switchboard isn't running, so the
 * landing page is always screenshot-able.
 */
export const OFFLINE_CAMPAIGN: CampaignDetail = {
  __typename: 'DefiUnited_PublicCampaign',
  slug: 'rseth-2026-04',
  name: 'rsETH Recovery',
  summary:
    'A coordinated DeFi industry response to the April 2026 rsETH incident, pooling pledges from major protocols and individuals to make affected users whole.',
  status: 'ACTIVE',
  incidentDate: '2026-04-18T00:00:00.000Z',
  targetAmount: '70000',
  totalPledged: '69550',
  totalReceived: '0',
  percentReceived: 0,
  pledgeCount: 10,
  dependenciesBlocking: 4,
  dependenciesResolved: 0,
  riskDisclaimer:
    'Pledges marked as governance-pending are non-binding until the originating DAO ratifies them on-chain. Confirmed contributions are commitments by individuals and entities to send funds to the published address. No tax, legal, or financial advice is provided. Track everything on-chain.',
  lastUpdateAt: new Date().toISOString(),
  affectedAsset: {
    __typename: 'DefiUnited_PublicAffectedAsset',
    symbol: 'rsETH',
    address: null,
    chainId: 1,
  },
  contributionAddresses: [
    {
      __typename: 'DefiUnited_PublicContributionAddress',
      chainId: 1,
      address: '0x0fCa5194baA59a362a835031d9C4A25970effE68',
      label: 'Ethereum Mainnet',
    },
  ],
  contributorsPublic: [
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: 'Mantle',
      contributorTrustLevel: 'VERIFIED',
      contributorWebsiteUrl: 'https://mantle.xyz',
      contributorTwitter: null,
      pledgedAmount: '30000',
      receivedAmount: null,
      assetSymbol: 'ETH',
      status: 'GOVERNANCE_PENDING',
      governanceProposalUrl: 'https://snapshot.box/#/mantle.eth',
      governancePlatform: 'SNAPSHOT',
      publicNotes: null,
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: 'Aave DAO',
      contributorTrustLevel: 'VERIFIED',
      contributorWebsiteUrl: 'https://aave.com',
      contributorTwitter: null,
      pledgedAmount: '25000',
      receivedAmount: null,
      assetSymbol: 'ETH',
      status: 'GOVERNANCE_PENDING',
      governanceProposalUrl: 'https://www.tally.xyz/gov/aave',
      governancePlatform: 'TALLY',
      publicNotes: null,
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: 'Ether.Fi',
      contributorTrustLevel: 'VERIFIED',
      contributorWebsiteUrl: 'https://ether.fi',
      contributorTwitter: null,
      pledgedAmount: '5000',
      receivedAmount: null,
      assetSymbol: 'ETH',
      status: 'GOVERNANCE_PENDING',
      governanceProposalUrl: 'https://gov.ether.fi/',
      governancePlatform: 'FORUM',
      publicNotes: null,
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: 'Lido',
      contributorTrustLevel: 'VERIFIED',
      contributorWebsiteUrl: 'https://lido.fi',
      contributorTwitter: null,
      pledgedAmount: '2500',
      receivedAmount: null,
      assetSymbol: 'ETH',
      status: 'GOVERNANCE_PENDING',
      governanceProposalUrl: 'https://snapshot.box/#/lido-snapshot.eth',
      governancePlatform: 'SNAPSHOT',
      publicNotes: null,
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: 'Stani Kulechov',
      contributorTrustLevel: 'VERIFIED',
      contributorWebsiteUrl: null,
      contributorTwitter: 'StaniKulechov',
      pledgedAmount: '5000',
      receivedAmount: null,
      assetSymbol: 'ETH',
      status: 'CONFIRMED',
      governanceProposalUrl: null,
      governancePlatform: null,
      publicNotes: null,
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: 'Golem Foundation',
      contributorTrustLevel: 'VERIFIED',
      contributorWebsiteUrl: 'https://golem.foundation',
      contributorTwitter: null,
      pledgedAmount: '1000',
      receivedAmount: null,
      assetSymbol: 'ETH',
      status: 'CONFIRMED',
      governanceProposalUrl: null,
      governancePlatform: null,
      publicNotes: null,
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: 'Emilio Frangella',
      contributorTrustLevel: 'VERIFIED',
      contributorWebsiteUrl: null,
      contributorTwitter: 'The3D_',
      pledgedAmount: '500',
      receivedAmount: null,
      assetSymbol: 'ETH',
      status: 'CONFIRMED',
      governanceProposalUrl: null,
      governancePlatform: null,
      publicNotes: null,
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: 'BGD Labs',
      contributorTrustLevel: 'VERIFIED',
      contributorWebsiteUrl: 'https://bgdlabs.com',
      contributorTwitter: null,
      pledgedAmount: '350',
      receivedAmount: null,
      assetSymbol: 'ETH',
      status: 'CONFIRMED',
      governanceProposalUrl: null,
      governancePlatform: null,
      publicNotes: null,
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: 'Frax Finance',
      contributorTrustLevel: 'VERIFIED',
      contributorWebsiteUrl: 'https://frax.finance',
      contributorTwitter: null,
      pledgedAmount: '100',
      receivedAmount: null,
      assetSymbol: 'ETH',
      status: 'PROPOSED',
      governanceProposalUrl: null,
      governancePlatform: null,
      publicNotes: null,
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: 'Ethena',
      contributorTrustLevel: 'VERIFIED',
      contributorWebsiteUrl: 'https://ethena.fi',
      contributorTwitter: null,
      pledgedAmount: '100',
      receivedAmount: null,
      assetSymbol: 'ETH',
      status: 'PROPOSED',
      governanceProposalUrl: null,
      governancePlatform: null,
      publicNotes: null,
    },
  ],
  dependenciesPublic: [
    {
      __typename: 'DefiUnited_PublicDependency',
      title: 'Mantle treasury vote',
      description: 'On-chain governance vote required to release pledged 30,000 ETH.',
      kind: 'GOVERNANCE_VOTE',
      status: 'IN_PROGRESS',
      externalRefUrl: 'https://snapshot.box/#/mantle.eth',
      externalRefProposalId: null,
      expectedResolution: null,
    },
    {
      __typename: 'DefiUnited_PublicDependency',
      title: 'Aave DAO ratification',
      description: 'Tally proposal to authorize the Aave Treasury contribution.',
      kind: 'GOVERNANCE_VOTE',
      status: 'OPEN',
      externalRefUrl: 'https://www.tally.xyz/gov/aave',
      externalRefProposalId: null,
      expectedResolution: null,
    },
    {
      __typename: 'DefiUnited_PublicDependency',
      title: 'Ether.Fi forum signal',
      description: 'Off-chain signal vote to authorize a 5,000 ETH commitment.',
      kind: 'GOVERNANCE_VOTE',
      status: 'OPEN',
      externalRefUrl: 'https://gov.ether.fi/',
      externalRefProposalId: null,
      expectedResolution: null,
    },
    {
      __typename: 'DefiUnited_PublicDependency',
      title: 'Lido easy-track motion',
      description: 'Snapshot motion to release Lido reserve allocation.',
      kind: 'GOVERNANCE_VOTE',
      status: 'OPEN',
      externalRefUrl: 'https://snapshot.box/#/lido-snapshot.eth',
      externalRefProposalId: null,
      expectedResolution: null,
    },
  ],
  recentUpdates: [],
  externalLinks: [],
}
