import type { CampaignDetail } from './queries'

/**
 * Hardcoded snapshot of the seeded `rseth-2026-04` campaign. Auto-generated
 * from the live Switchboard projection so this fallback always matches the
 * shape & values that operators see when GraphQL is unreachable.
 */
export const OFFLINE_CAMPAIGN: CampaignDetail = {
  __typename: 'DefiUnited_PublicCampaign',
  slug: "rseth-2026-04",
  name: "rsETH Recovery",
  summary: "Coordinated relief effort led by Aave service providers following the April 18 rsETH incident. The aim is to restore rsETH's backing, which will help normalize market conditions across multiple networks.",
  status: "ACTIVE",
  incidentDate: "2026-04-18T00:00:00.000Z",
  targetAmount: "100000",
  totalPledged: "102798",
  totalReceived: "102648",
  percentReceived: 102.65,
  pledgeCount: 18,
  dependenciesBlocking: 2,
  dependenciesResolved: 1,
  riskDisclaimer: "Contributions depend on technical and governance actions by third parties, including KelpDAO reopening withdrawals and Arbitrum Security Council releasing frozen ETH. Success remains uncertain and contributors assume associated risks.",
  lastUpdateAt: "2026-04-27T13:12:59.815Z",
  affectedAsset: {
    __typename: 'DefiUnited_PublicAffectedAsset',
    symbol: "rsETH",
    address: null,
    chainId: 1,
  },
  contributionAddresses: [
    {
      __typename: 'DefiUnited_PublicContributionAddress',
      chainId: 1,
      address: "0x0fCa5194baA59a362a835031d9C4A25970effE68",
      label: "Ethereum Mainnet",
    },
  ],
  contributorsPublic: [
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: "Mantle",
      contributorTrustLevel: "VERIFIED",
      contributorWebsiteUrl: "https://mantle.xyz",
      contributorTwitter: "@mantle_official",
      pledgedAmount: "30000",
      receivedAmount: "30000",
      assetSymbol: "ETH",
      status: "RECEIVED",
      governanceProposalUrl: "https://snapshot.box/#/mantle.eth",
      governancePlatform: "SNAPSHOT",
      publicNotes: "Largest pledge to the relief effort. Pending Mantle governance approval.",
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: "Aave DAO",
      contributorTrustLevel: "VERIFIED",
      contributorWebsiteUrl: "https://aave.com",
      contributorTwitter: "@aave",
      pledgedAmount: "25000",
      receivedAmount: "25000",
      assetSymbol: "ETH",
      status: "RECEIVED",
      governanceProposalUrl: "https://www.tally.xyz/gov/aave",
      governancePlatform: "TALLY",
      publicNotes: "Aave DAO commitment via on-chain governance proposal.",
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: "Ether.Fi",
      contributorTrustLevel: "VERIFIED",
      contributorWebsiteUrl: "https://ether.fi",
      contributorTwitter: "@ether_fi",
      pledgedAmount: "5000",
      receivedAmount: "5000",
      assetSymbol: "ETH",
      status: "RECEIVED",
      governanceProposalUrl: "https://gov.ether.fi/",
      governancePlatform: "FORUM",
      publicNotes: "Ether.Fi committed contribution, awaiting on-chain action.",
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: "Lido",
      contributorTrustLevel: "VERIFIED",
      contributorWebsiteUrl: "https://lido.fi",
      contributorTwitter: "@LidoFinance",
      pledgedAmount: "2500",
      receivedAmount: "2500",
      assetSymbol: "ETH",
      status: "RECEIVED",
      governanceProposalUrl: "https://snapshot.box/#/lido-snapshot.eth",
      governancePlatform: "SNAPSHOT",
      publicNotes: "Lido DAO contribution pending governance vote.",
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: "Stani Kulechov",
      contributorTrustLevel: "VERIFIED",
      contributorWebsiteUrl: "https://stani.lens",
      contributorTwitter: "@StaniKulechov",
      pledgedAmount: "5000",
      receivedAmount: "5000",
      assetSymbol: "ETH",
      status: "RECEIVED",
      governanceProposalUrl: null,
      governancePlatform: null,
      publicNotes: "Personal commitment from Stani Kulechov, founder of Aave.",
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: "Golem Foundation",
      contributorTrustLevel: "VERIFIED",
      contributorWebsiteUrl: "https://golem.foundation",
      contributorTwitter: "@golemproject",
      pledgedAmount: "1000",
      receivedAmount: "850",
      assetSymbol: "ETH",
      status: "RECEIVED",
      governanceProposalUrl: null,
      governancePlatform: null,
      publicNotes: "Golem Foundation + Project commitment.",
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: "Emilio Frangella",
      contributorTrustLevel: "VERIFIED",
      contributorWebsiteUrl: null,
      contributorTwitter: "@emilianobonassi",
      pledgedAmount: "500",
      receivedAmount: "500",
      assetSymbol: "ETH",
      status: "RECEIVED",
      governanceProposalUrl: null,
      governancePlatform: null,
      publicNotes: "Personal contribution from Emilio Frangella (BGD Labs).",
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: "BGD Labs (Ernesto)",
      contributorTrustLevel: "VERIFIED",
      contributorWebsiteUrl: "https://bgdlabs.com",
      contributorTwitter: "@bgdlabs",
      pledgedAmount: "350",
      receivedAmount: "350",
      assetSymbol: "ETH",
      status: "RECEIVED",
      governanceProposalUrl: null,
      governancePlatform: null,
      publicNotes: "BGD Labs (Ernesto) commitment to the relief effort.",
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: "Arbitrum DAO",
      contributorTrustLevel: "ANNOUNCED",
      contributorWebsiteUrl: "https://arbitrum.foundation",
      contributorTwitter: "arbitrum",
      pledgedAmount: "30765",
      receivedAmount: "30765",
      assetSymbol: "ETH",
      status: "RECEIVED",
      governanceProposalUrl: "https://www.tally.xyz/gov/arbitrum",
      governancePlatform: "TALLY",
      publicNotes: null,
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: "Kelp DAO",
      contributorTrustLevel: "ANNOUNCED",
      contributorWebsiteUrl: "https://kelpdao.xyz",
      contributorTwitter: "KelpDAO",
      pledgedAmount: "2000",
      receivedAmount: "2000",
      assetSymbol: "ETH",
      status: "RECEIVED",
      governanceProposalUrl: null,
      governancePlatform: null,
      publicNotes: null,
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: "Frax Finance",
      contributorTrustLevel: "ANNOUNCED",
      contributorWebsiteUrl: "https://frax.finance",
      contributorTwitter: "@fraxfinance",
      pledgedAmount: "0",
      receivedAmount: null,
      assetSymbol: "ETH",
      status: "CONFIRMED",
      governanceProposalUrl: null,
      governancePlatform: null,
      publicNotes: "Amount TBD — confirmed contributor pending finalisation.",
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: "Ethena",
      contributorTrustLevel: "ANNOUNCED",
      contributorWebsiteUrl: "https://ethena.fi",
      contributorTwitter: "@ethena_labs",
      pledgedAmount: "0",
      receivedAmount: null,
      assetSymbol: "ETH",
      status: "CONFIRMED",
      governanceProposalUrl: null,
      governancePlatform: null,
      publicNotes: "Amount TBD — confirmed contributor pending finalisation.",
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: "LayerZero",
      contributorTrustLevel: "ANNOUNCED",
      contributorWebsiteUrl: "https://layerzero.network",
      contributorTwitter: "LayerZero_Labs",
      pledgedAmount: "0",
      receivedAmount: null,
      assetSymbol: "ETH",
      status: "CONFIRMED",
      governanceProposalUrl: null,
      governancePlatform: null,
      publicNotes: "Amount TBD — confirmed contributor pending finalisation.",
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: "Ink Foundation",
      contributorTrustLevel: "ANNOUNCED",
      contributorWebsiteUrl: "https://inkonchain.com",
      contributorTwitter: "inkonchain",
      pledgedAmount: "0",
      receivedAmount: null,
      assetSymbol: "ETH",
      status: "CONFIRMED",
      governanceProposalUrl: null,
      governancePlatform: null,
      publicNotes: "Amount TBD — confirmed contributor pending finalisation.",
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: "Tydro",
      contributorTrustLevel: "ANNOUNCED",
      contributorWebsiteUrl: "https://tydro.io",
      contributorTwitter: null,
      pledgedAmount: "0",
      receivedAmount: null,
      assetSymbol: "ETH",
      status: "CONFIRMED",
      governanceProposalUrl: null,
      governancePlatform: null,
      publicNotes: "Amount TBD — confirmed contributor pending finalisation.",
    },
    {
      __typename: 'DefiUnited_PublicPledge',
      contributorDisplayName: "Anonymous Coalition Reserve",
      contributorTrustLevel: "ANNOUNCED",
      contributorWebsiteUrl: null,
      contributorTwitter: null,
      pledgedAmount: "683",
      receivedAmount: "683",
      assetSymbol: "ETH",
      status: "RECEIVED",
      governanceProposalUrl: null,
      governancePlatform: null,
      publicNotes: "Aggregated contributions from anonymous coalition members and small donors.",
    },
  ],
  dependenciesPublic: [
    {
      __typename: 'DefiUnited_PublicDependency',
      title: "KelpDAO bridge remediation",
      description: "LayerZero DVN topology hardened from 1-of-1 to N-of-M after the April 18 exploit. Bridge audit complete; protocol-level remediation deployed.",
      kind: "OPERATIONAL",
      status: "RESOLVED",
      externalRefUrl: "https://kelpdao.xyz/",
      externalRefProposalId: null,
      expectedResolution: null,
    },
    {
      __typename: 'DefiUnited_PublicDependency',
      title: "Arbitrum DAO release of $71M frozen exploiter funds",
      description: "Arbitrum Security Council froze 30,766 ETH (~$71M) of the exploiter's holdings post-incident. Aave Labs and KelpDAO have formally requested the Arbitrum DAO to release these funds back to the recovery treasury. Vote pending.",
      kind: "COUNCIL_ACTION",
      status: "IN_PROGRESS",
      externalRefUrl: "https://arbitrum.foundation/security-council",
      externalRefProposalId: null,
      expectedResolution: null,
    },
    {
      __typename: 'DefiUnited_PublicDependency',
      title: "Aave DAO governance approval",
      description: "Aave DAO must approve the 25,000 ETH commitment via on-chain governance before funds can be released.",
      kind: "GOVERNANCE_VOTE",
      status: "IN_PROGRESS",
      externalRefUrl: "https://www.tally.xyz/gov/aave",
      externalRefProposalId: "aave-defi-united-2026-04",
      expectedResolution: null,
    },
  ],
  recentUpdates: [
    {
      __typename: 'DefiUnited_PublicStatusUpdate',
      id: "c5600ee2-cfc1-49eb-abe0-588aff53eb9d",
      publishedAt: "2026-04-27T11:45:00.000Z",
      title: "Goal reached — coalition target exceeded",
      body: "All major DAO pledges and anonymous coalition contributions have been received on-chain. Total received now exceeds the 100,000 ETH recovery threshold. The coalition is moving to the distribution phase to make affected rsETH holders whole.",
      metricsTotalPledged: "102798",
      metricsTotalReceived: "102648",
      externalAnnouncements: [
      ],
    },
    {
      __typename: 'DefiUnited_PublicStatusUpdate',
      id: "5a2a1010-50a4-44ec-93db-bb9dbdfa8f94",
      publishedAt: "2026-04-27T09:30:00.000Z",
      title: "70M ETH recovered — Arbitrum DAO release request live",
      body: "Aave Labs and KelpDAO have formally requested the Arbitrum DAO to release 30,766 ETH (~71M USD) of the exploiter's frozen holdings on Arbitrum. Combined with on-chain pledges already received, ~70M ETH is now back in coordinated custody. Stani Kulechov: recovery is an orderly process.",
      metricsTotalPledged: "69550",
      metricsTotalReceived: "8350",
      externalAnnouncements: [
      ],
    },
    {
      __typename: 'DefiUnited_PublicStatusUpdate',
      id: "6feee575-1683-4b83-8fb7-426a7795491c",
      publishedAt: "2026-04-25T15:00:00.000Z",
      title: "DeFi United launches recovery effort",
      body: "Following the April 18 rsETH incident, a coalition of major DeFi service providers has formed DeFi United — a coordinated relief effort to restore rsETH's backing and normalize market conditions across networks.\n\n**Pledges to date**\n\n- Mantle: 30,000 ETH (governance pending)\n- Aave DAO: 25,000 ETH (governance pending)\n- Ether.Fi: 5,000 ETH (governance pending)\n- Lido: 2,500 ETH (governance pending)\n- Stani Kulechov: 5,000 ETH (confirmed)\n- Golem Foundation + Project: 1,000 ETH (confirmed)\n- Emilio Frangella: 500 ETH (confirmed)\n- BGD Labs + Ernesto: 350 ETH (confirmed)\n\nAdditional commitments are being negotiated with Frax Finance, Ethena, LayerZero, Ink Foundation, and others.\n\n**Risks**\n\nThis effort depends on technical and governance actions by third parties — KelpDAO must reopen withdrawals, and the Arbitrum Security Council must release frozen ETH. Contributors assume the associated risks.\n\nContribute via Ethereum Mainnet at `0x0fCa5194baA59a362a835031d9C4A25970effE68`.",
      metricsTotalPledged: "70000",
      metricsTotalReceived: "6850",
      externalAnnouncements: [
      ],
    },
    {
      __typename: 'DefiUnited_PublicStatusUpdate',
      id: "a6d7ddab-34dc-4275-a771-21ef5a6f2571",
      publishedAt: "2026-04-25T14:00:00.000Z",
      title: "Aave DAO proposes 25,000 ETH to cover rsETH shortfall",
      body: "Tally proposal AIP-2026-04-25 is live. If ratified, the Aave Treasury commits 25,000 ETH — bringing the coalition past 99% of target. Vote ends 2026-04-30.",
      metricsTotalPledged: "69550",
      metricsTotalReceived: "8350",
      externalAnnouncements: [
      ],
    },
    {
      __typename: 'DefiUnited_PublicStatusUpdate',
      id: "d5b9bec9-16d5-4851-86c3-e5b72b9e4564",
      publishedAt: "2026-04-22T10:00:00.000Z",
      title: "First receipts confirmed on-chain — 7,500 ETH",
      body: "Lido (2,500 ETH, post easy-track ratification) and Stani Kulechov (5,000 ETH direct) have transferred funds to the campaign treasury. Pledge to receipt reconciliation handled automatically by the campaign processor.",
      metricsTotalPledged: "69550",
      metricsTotalReceived: "7500",
      externalAnnouncements: [
      ],
    },
  ],
  externalLinks: [
    { __typename: 'DefiUnited_PublicExternalLink', label: "DeFi United landing page", url: "https://defiunited.world/" },
  ],
  recentReceipts: [],
  recentOnchainTransfers: [],
  onchainLiveBalance: null,
  pendingReceiptsEthEquivalent: null,
}
